version: 0.2
env:
  secrets-manager:
    DOCKER_HUB_PASS: "CHnMqs7@hNhNM%V"
    DOCKER_HUB_USERNAME: "ovaldezb"
phases:
  pre_build:
    commands:
      - echo Logging in the Amazon ECR
      - echo docker login
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 121162867777.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=121162867777.dkr.ecr.us-east-2.amazonaws.com/spring-demo-ecr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on ´date´
      - echo building the jar file
      - mvn clean install
      - echo building the docker image
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build completed on ´date´
      - echo pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo writing image definitions file...
      - DOCKER_CONTAINER_NAME=spring-demo-ecr
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/Paguitos-1.0.0.jar